[project]
name = 'Blockchain-Based-Specialized-Antique-Verification'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.expert-authenticator]
path = 'contracts/expert-authenticator.clar'
clarity_version = 2
epoch = 2.5

[contracts.item-registration]
path = 'contracts/item-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.ownership-history]
path = 'contracts/ownership-history.clar'
clarity_version = 2
epoch = 2.5

[contracts.restoration-tracking]
path = 'contracts/restoration-tracking.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
